pre_upgrade() {
    /usr/bin/rstudio-server offline
}

post_upgrade() {
    /usr/bin/rstudio-server online
}

pre_remove() {
    echo "Leftover files may reside in /var/log/rstudio-server and /var/lib/rstudio-server"
}

post_remove() {
    if getent passwd rstudio-server >/dev/null 2>&1; then
        userdel -f rstudio-server
    fi
    if getent group rstudio-server >/dev/null 2>&1; then
        groupdel rstudio-server
    fi
}

