post_install() {
  # make install complete
  ln -s /usr/lib/rstudio/RStudio /usr/bin/rstudio
  #echo "install R packages"
  # R CMD INSTALL /usr/lib/rstudio/R/packages/yaml_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/digest_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/htmltools_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/evaluate_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/formatR_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/highr_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/mime_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/markdown_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/stringr_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/knitr_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/rmarkdown_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/packrat_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/Rcpp_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/httpuv_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/bitops_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/caTools_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/RJSONIO_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/xtable_*.tar.gz
  # R CMD INSTALL /usr/lib/rstudio/R/packages/shiny_*.tar.gz
  # rm -rf /usr/lib/rstudio/R/packages/*.tar.gz
  echo "done"
}

post_upgrade() {
  rm -r /usr/bin/rstudio
  post_install $1
}

post_remove () {
  rm -r /usr/bin/rstudio
  echo -n "updating desktop mime database ... "
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
  update-mime-database usr/share/mime &> /dev/null
  # echo "remove R packages"
  # R CMD REMOVE yaml
  # R CMD REMOVE digest
  # R CMD REMOVE htmltools
  # R CMD REMOVE evaluate
  # R CMD REMOVE formatR
  # R CMD REMOVE highr
  # R CMD REMOVE mime
  # R CMD REMOVE markdown
  # R CMD REMOVE stringr
  # R CMD REMOVE knitr
  # R CMD REMOVE rmarkdown
  # R CMD REMOVE packrat
  # R CMD REMOVE Rcpp
  # R CMD REMOVE httpuv
  # R CMD REMOVE bitops
  # R CMD REMOVE caTools
  # R CMD REMOVE RJSONIO
  # R CMD REMOVE xtable
  # R CMD REMOVE shiny
  echo "done."
}
